const { withAppBuildGradle } = require('expo/config-plugins');

// Produces one release APK per CPU architecture (app-armeabi-v7a-release.apk,
// app-arm64-v8a-release.apk, app-x86-release.apk, app-x86_64-release.apk) in
// android/app/build/outputs/apk/release/, instead of a single "fat" APK
// bundling all architectures' native libraries.
//
// android/ is regenerated by `expo prebuild` (Continuous Native Generation),
// so this has to be injected via a config plugin rather than a one-off manual
// edit to android/app/build.gradle, which would be wiped on the next prebuild.
const SPLITS_BLOCK = `
    splits {
        abi {
            reset()
            enable true
            universalApk false
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
`;

function withAbiSplits(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') return config;

    let contents = config.modResults.contents;
    if (contents.includes('splits {')) return config;

    const androidBlockIndex = contents.indexOf('\nandroid {');
    if (androidBlockIndex === -1) return config;

    const insertAt = androidBlockIndex + '\nandroid {'.length;
    contents =
      contents.slice(0, insertAt) + SPLITS_BLOCK + contents.slice(insertAt);

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withAbiSplits;
