const { withProjectBuildGradle } = require('expo/config-plugins');

// Notifee ships its Android native module (app.notifee:core) as a local flat
// Maven repo bundled inside its own npm package, not on Google/Maven
// Central/JitPack — Gradle can't resolve it without this repo declared.
// See: node_modules/@notifee/react-native/android/libs
//
// android/ is regenerated by `expo prebuild` (Continuous Native Generation),
// so this has to be injected via a config plugin rather than a one-off manual
// edit to android/build.gradle, which would be wiped on the next prebuild.
const NOTIFEE_MAVEN_LINE =
  "    maven { url(\"$rootDir/../node_modules/@notifee/react-native/android/libs\") }\n";

function withNotifeeAndroidMaven(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') return config;

    let contents = config.modResults.contents;
    if (contents.includes('@notifee/react-native/android/libs')) return config;

    const allprojectsIndex = contents.indexOf('allprojects {');
    if (allprojectsIndex === -1) return config;

    const repositoriesIndex = contents.indexOf('repositories {', allprojectsIndex);
    if (repositoriesIndex === -1) return config;

    const insertAt = repositoriesIndex + 'repositories {'.length;
    contents =
      contents.slice(0, insertAt) +
      '\n' +
      NOTIFEE_MAVEN_LINE +
      contents.slice(insertAt);

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withNotifeeAndroidMaven;
